replicaCount: 1

configuration:
  codexdocsrc:
    title: "CodeX Docs"
    description: "A block-styled editor with clean JSON output"
    landingFrameSrc: "https://codex.so/editor?frame=1" 
    menu:
      - "Guides"
      - "API"
      - "Plugins"
      - title: "Support Project"
        uri: "/support"
    misprintsChatId: 
    startPage:
    yandexMetrikaId:
    carbon:
      placement:
      serve:
  production:
    port: 3000
    database: ".db"
    rcFile: "./.codexdocsrc"
    "uploads": "public/uploads"
    "secret": "iamasecretstring"

image:
  repository: ghcr.io/codex-team/codex-docs
  pullPolicy: Always
  tag: "stage"

imagePullSecrets: []
fullnameOverride: "codex-docs"

serviceAccount:
  create: false
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}