#replicaCount: 1

configuration:
  codexdocsrc:
    title: "CodeX Docs"
    description: "A block-styled editor with clean JSON output"
    landingFrameSrc: "https://codex.so/editor?frame=1" 
    menu:
      - "Guides"
      - "API"
      - "Plugins"
      - title: "Support Project"
        uri: "/support"
    misprintsChatId: 
    startPage:
    yandexMetrikaId:
    carbon:
      placement:
      serve:
  production:
    port: 3000
    database: "/mnt/db"
    rcFile: "./.codexdocsrc"
    "uploads": "/usr/src/app/public/uploads"
    "secret": "iamasecretstring"

# Authentication parameters
auth:
  # Auth password
  # Defaults to a random 20-character alphanumeric string if not set
  #
  password: ""
  # The name of an existing secret with auth credentials
  # NOTE: When it's set, the previous `auth.password` parameter is ignored
  #
  existingSecret: ""
  # Password key to be retrieved from existing secret
  # NOTE: ignored unless `auth.existingSecret` parameter is set
  #
  existingSecretPasswordKey: ""

image:
  repository: ghcr.io/codex-team/codex.docs
  pullPolicy: Always
  tag: ""

imagePullSecrets: []
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: codex-docs.local
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: web
              port:
                number: 3000
  tls: []

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
