apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  codexdocsrc: |-
    {{ .Values.configuration.codexdocsrc | toJson }}
  production.json: |-
    {{ .Values.configuration.production | toJson }}