apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "codexdocs.fullname" . }}
  labels:
    {{- include "codexdocs.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "codexdocs.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "codexdocs.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
          - name: config
            configMap:
              defaultMode: 420
              name: {{ .Release.Name }}-config
          - name: {{ include "codexdocs.fullname" . }}-db
            persistentVolumeClaim:
              claimName: {{ include "codexdocs.fullname" . }}-db
          - name: {{ include "codexdocs.fullname" . }}-uploads
            persistentVolumeClaim:
              claimName: {{ include "codexdocs.fullname" . }}-uploads
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: config
              mountPath: /usr/src/app/.codexdocsrc
              subPath: "codexdocsrc"
            - name: config
              mountPath: /usr/src/app/config/production.json
              subPath: "production.json"
            - name: {{ include "codexdocs.fullname" . }}-db
              mountPath: {{ .Values.configuration.production.database }}
            - name: {{ include "codexdocs.fullname" . }}-uploads
              mountPath:  {{ .Values.configuration.production.uploads }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
