{{- if not .Values.auth.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "codexdocs.fullname" . }}
  labels:
    {{- include "codexdocs.labels" . | nindent 4 }}
type: Opaque
data:
  docs-password: {{ include "codexdocs.password" . | b64enc | quote }}
{{- end -}}