apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "codexdocs.fullname" . }}-db
  labels:
    {{- include "codexdocs.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "codexdocs.fullname" . }}-uploads
  labels:
    {{- include "codexdocs.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage:  5Gi